### ISSUE TITLE
Dom manipulation library wrapping content in DOCTYPE and HTML tags - potentially unwanted.

### ISSUE THREAD

**Issue by netcarver** [ocorreiododiogo/PW-removeHeights#2]
Hi @ocorreiododiogo,

I have just been made aware that this method of doing the dom manipulations wraps the HTML fragment being operated on with a doctype and open+close HTML tags. Probably not what you want. I've implemented changes to strip these out in my derived module, you may want to [take a look](https://github.com/netcarver/TextformatterFluidImages/commit/1ebc4e2536d38120d82be86a5baef56c7b4f3595).

**Comment by ocorreiododiogo** [comment]
You're right, thanks! I actually had this corrected on other modules but used another method that you may want to check out yourself https://stackoverflow.com/a/22490902/1930250

**Comment by ocorreiododiogo** [comment]
Fixed. I will close this issue.

In case you want to fix it on yours, all you have to do is add those options when calling the loadHTML method:
`$dom->loadHTML(mb_convert_encoding($str, 'HTML-ENTITIES', 'UTF-8'), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD)`
